import Providers from '@/app/providers';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import '@/lib/config/envConfig';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <Providers>
        <body
          className={cn([inter.variable, 'font-inter text-base font-normal'])}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
